services:
  go-chatgpt-api:
    build: .
    container_name: go-chatgpt-api
    image: leonardpark/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Shanghai
      - PORT=8080
      - NINJA_URL=http://127.0.0.1:7999
    restart: unless-stopped
