name: Release

on:
  push:
    branches:
      - 'main'

env:
  PLATFORMS: ${{ vars.PLATFORMS || 'linux/amd64,linux/arm64' }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/HongKong'
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GT_TOKEN }}
        with:
          tag_name: release-${{ env.CURRENT_DATETIME }}
          release_name: Release ${{ env.CURRENT_DATETIME }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./go-chatgpt-api
          asset_name: go-chatgpt-api
          asset_content_type: application/x-mach-binary